// Helper functions to reduce boilerplate and obviate constants as action.type
import { createAction, ActionType } from "typesafe-actions";

import { IMessage, TAllMessages } from "./messagesTypes";

export const fetchMessagesAction = createAction(
    "messages/FETCH_MESSAGES",
    (action) => {
        return () => action();
    }
);

export const populateMessagesAction = createAction(
    "messages/POPULATE_MESSAGES",
    (action) => {
        return (messages: TAllMessages) => action(messages);
    }
);

export const clearMessagesAction = createAction("messages/CLEAR_MESSAGES");

export const deleteMessage = createAction(
    "messages/DELETE_MESSAGE",
    (action) => {
        return (messageID: IMessage["_id"]) => action(messageID);
    }
);

// Union type for user actions generated by helper utility.  Reducer uses this to
// correctly type its 'action' parameter.
const messagesActions = {
    populateMessagesAction,
    clearMessagesAction,
    deleteMessage
};

export type TMessagesAction = ActionType<typeof messagesActions>;
