// Helper functions to reduce boilerplate and obviate constants as action.type
import { createAction, ActionType } from 'typesafe-actions';

import { IMessage, AllMessages } from './messagesTypes';

export const populateMessages = createAction('messages/POPULATE_MESSAGES', action => {
	return (messages: AllMessages) => action(messages);
});

export const clearMessages = createAction('messages/CLEAR_MESSAGES');

export const deleteMessage = createAction('messages/DELETE_MESSAGE', action => {
	return (messageID: IMessage['_id']) => action(messageID);
});

// Union type for user actions generated by helper utility.  Reducer uses this to 
// correctly type its 'action' parameter.
const messagesActions = {
	populateMessages,
	clearMessages,
	deleteMessage
};

export type MessagesAction = ActionType<typeof messagesActions>;