// Helper functions to reduce boilerplate and obviate constants as action.type
import { createAction, ActionType } from 'typesafe-actions';

import { INetUser } from '../../utils/networkTypes';

export const populateUser = createAction('user/POPULATE_USER', action => {
	return (userData: INetUser) => action(userData);
});

export const depopulateUser = createAction('user/DEPOPULATE_USER')

// Union type for user actions generated by helper utility.  Reducer uses this to 
// correctly type its 'action' parameter.
const userActions = {
	populateUser,
	depopulateUser
}

export type UserAction = ActionType<typeof userActions>;