// Helper functions to reduce boilerplate and obviate constants as action.type
import { createAction, ActionType } from "typesafe-actions";

import { IUserData } from "./userTypes";

export const fetchUserAction = createAction("user/FETCH_USER", (action) => {
    return () => action();
});

export const populateUserAction = createAction(
    "user/POPULATE_USER",
    (action) => {
        return (userData: IUserData) => action(userData);
    }
);

export const depopulateUserAction = createAction("user/DEPOPULATE_USER");

// Union type for user actions generated by helper utility.  Reducer uses this to
// correctly type its 'action' parameter.
const userActions = {
    fetchUserAction,
    populateUserAction,
    depopulateUserAction
};

export type TUserAction = ActionType<typeof userActions>;
